### ISSUE TITLE
Implement an async flow

### ISSUE THREAD

**Issue by sadasant** [smartprocure/futil-js#107]
I think it can be like this:

```js
export let asyncFlow = (head, ...tail) => async (...params) => asyncFlow(...tail)(await head(...params))
```

**Comment by sadasant** [comment]
Here's a working version made by a friend: `const asyncFlow = (...fns) => x => fns.reduce((v, f) => v.then(f), Promise.resolve(x))`

**Comment by daedalus28** [comment]
Ramda has stuff like pipeP and composeP, but interestingly they're considering removing it:

https://github.com/ramda/ramda/pull/1869

**Comment by daedalus28** [comment]
This is covered by #411 
It also allows for automatic Promise.all/promiseProps calls so you can generally just flow together anything async and it will work without thinking about promises. `flowAsyncDeep` is wonderfully magical. It also only becomes async if necessary, so you can use if safely in sync scenarios without needing an extra await.

**Comment by daedalus28** [comment]
`flowAsync` is publishing in 1.74.0 right now 😄
