### ISSUE TITLE
Make a fancy logo

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/futil-js#110]
Every real library has a fancy logo. We clearly need one.

Maybe something looks like a borg cube?

**Comment by giulianok** [comment]
What about this one?

![dbf0672e-2ca3-4df0-b7c9-05c46be57007](https://user-images.githubusercontent.com/8062245/28591692-97fa0f1e-7154-11e7-8185-dc858f163c6c.png)

**Comment by daedalus28** [comment]
Not bad, it's got a nice borg + cylon vibe going for it 😄 

We should probably put the `-js` in the logo too since we don't have the `futil` package name on npm, just `futil-js`

**Comment by daedalus28** [comment]
With some luck, we might actually be able to get the `futil` npm package name: https://github.com/joaonuno/futil-js/issues/1

**Comment by giulianok** [comment]
New logo :)

<img width="684" alt="futil-logo-2" src="https://user-images.githubusercontent.com/8062245/28718527-796382ac-7374-11e7-98a3-9791223042a4.png">
<img width="404" alt="futil-logo" src="https://user-images.githubusercontent.com/8062245/28718526-795d071a-7374-11e7-8649-bb759c7523b9.png">

**Comment by daedalus28** [comment]
Great stuff! Can you open a PR updating the readme with our shiny new logo at the top?

**Comment by giulianok** [comment]
Sure, doing that

**Comment by daedalus28** [comment]
This is done 👍
