### ISSUE TITLE
Real Docs Website

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/futil-js#111]
We should have a real docs site like lodash, ramda, etc.

Currently, we're waiting on lodash 5 progress since we'd like to do the same thing as lodash, but their doc generation is currently unclear while they're working on v5.

**Comment by daedalus28** [comment]
We do have smartprocure.github.io/futil-js

**Comment by daedalus28** [comment]
The goal is to use the shiny new [exploreAPI](https://runkit.com/daedalus28/explore-api-futil-candidate) method to provide a super interactive docs site that lets you search by name, full-text search on the method docs (using our inverted index/highlighting stuff), or by typing in inputs and expected output.

The plan is to swap our docs to a json format instead of giant markdown file.

**Comment by stellarhoof** [comment]
> The plan is to swap our docs to a json format

Have we discarded JSDoc-style documentation?

Ideally there'd be a parser library that extracts documentation from comments like JSDoc and give us the parse tree so we have the flexibility to "render" our documentation however we want. I haven't found any so far.

I briefly took a look at https://github.com/mozilla/sphinx-js, but it has sphinx as an external dep.

**Comment by daedalus28** [comment]
We evaluated using something like JSDoc, but there are a few things we'd like to do that aren't super easy with JSDoc, like categorizing methods (see https://stackoverflow.com/questions/48035855/how-to-create-categories-in-jsdoc) and the fact that we'd like to use our unit tests as inlined examples. To do that, we'd need to write code to extend the JSON output from a parser anyway, so we'd still likely be authoring a json doc for our methods anyway. It seems like all it would buy us is the ability to use the JSDoc format itself, which seems a bit heavy-handed - and aesthetically it's kinda ugly with all those asterisks 😂

**Comment by daedalus28** [comment]
Updating this thread with everything that's happening now - _lots_ of cool stuff!

Docs will be authored with JSDoc inlined, pulling in unit tests by name for examples. The new website is a super modern react app build on ChakraUI and we'll still generate a markdown readme from the jsdoc. PRs coming soon!

**Comment by daedalus28** [comment]
This is live now!

https://smartprocure.github.io/futil-js/

**Comment by stellarhoof** [comment]
Nice! Only after 5 years :)

So I suppose we can close this issue now.
