### ISSUE TITLE
Release on npm as `futil`

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/futil-js#117]
Thanks to the awesome @joaonuno, we now have the `futil` package name!

This ticket is to track all the steps we need to take to make it happen

- [ ] Rename this repo to smartprocure/futil
- [ ] Publish a new version of futil-js with the new repo name and a big deprecation warning at the top of the readme (and ideally with our fancy new logo to keep brand identity consistent)
- [ ] Change package name and release a new version (major or feature? @sean-c is our resident semantic-versioning expert)
- [ ] Run npm deprecate on the futil-js version
- [ ] Update all dependent libraries/projects 
- [ ] Enjoy the awesomeness of our new package name

**Comment by daedalus28** [comment]
We should also complete #115 first since our npm release history will not be obvious after we do this

**Comment by daedalus28** [comment]
Alternatively, we can publish as _both_ as described here: https://github.com/npm/npm/issues/16054

**Comment by lsm** [comment]
Yes.  Maybe publish both for a while.  We can add a deprecated warning to the `futil-js` and eventually remove it from npm.

**Comment by daedalus28** [comment]
It seems like we could just add a quick npm script for publishing which locally changes the package name to `futil` in package.json and runs publish so we just publish as both for now

**Comment by daedalus28** [comment]
We are now officially releasing with both packages. I think we can close this now.
