### ISSUE TITLE
Add our tabSort

### ISSUE THREAD

**Issue by sadasant** [smartprocure/futil-js#121]
We use this sort in several places, let's add it here:

```
let sortByKey = _.curry((key, tabs) => _.sortBy(obj => {
  let ord = _.get(key, obj)
  return ord >= 0 ? ord : ord < 0 ? (tabs.length * 2) + ord
    : tabs.length
}, tabs)
```

**Comment by tvsudhir** [comment]
Few questions @sadasant ... (if u have time then plz answer)
1 - Lodash documentation for `_.sortBy` says it will take `array` first and then `function`
https://lodash.com/docs/#sortBy
From currying perspective it is always better to have method signature `_.sortBy(fn, array)`.
So, is that code snippet, actual code which runs in production ??? How come ?
If it is pseudo code then, it is fine.

Same difference in method signature for `_.get`. The usage of parameters is reverse
https://lodash.com/docs/#get

May be that I am missing something very obvious ... Plz point out.

**Comment by daedalus28** [comment]
Hi @tvsudhir! You're right about the argument order for lodash, but there is a version of lodash called lodash/fp which flips the argument order, curries everything, and is immutable by default. `futil-js` is designed to be a companion to lodash/fp (which is included in every lodash install) and we use that version pretty heavily here. The docs for lodash/fp can be found [here](https://github.com/lodash/lodash/wiki/FP-Guide)

**Comment by sadasant** [comment]
@tvsudhir hi! It's great to see you interested in our project! Please let us know if you have any other question!

**Comment by tvsudhir** [comment]
@daedalus28 , @sadasant ... good to see some responses.
One of my complaints with `lodash` over `ramdajs` was the order of parameter.
Good to know about `lodash/fp` ... 

The guys behind `ramdajs` are all for functional style and guys behind `lodash` were all for performance so it was a difficult pick ...

Thanks for clarification.

And just one point on the code the function returns `tabs.length` only if `ord` is `undefined` or `null` or `''` (so any falsy value in JavaScript) which is kind of hidden in syntax. 
Took few minutes to understand when a value could be neither >= 0 nor < 0 (was so strange).
So a simple IF condition to take that concern out of convoluted double ternary would be great.

I like functional style of code. Was checking who all are really putting effort (or see value) in this type of coding.
And I stumbled upon this repo.

**Comment by daedalus28** [comment]
Just so this doesn't get too stale, here's a much more verbose implementation with an explanation:

```js
// Order can be on of the three things: [0 - size] for left ordering, [-size, -1] for right ordering, or any non numeric value to be placed in the middle of those sections
// A common use case would be sorting table columns, where you'd want to send some to the front and others to the back and the let the rest fall in place
let comparator = _.curry((size, order) => {
  // Unspecified order goes to the "middle"
  if (!_.isNumber(order)) return size
  // Positive number puts it at the beginning from left to right (so 0 is first, 1 is second)
  if (order >= 0) return Math.min(order, size)
  // Negative number puts it at the end from right to left (so -1 is the end, -2 is one from the end)
  // Note that we're basing the negative index off size * 2 in case every item is ordered negative
  if (order < 0) return size * 2 + order
})
let sortByKey = _.curry((key, items) =>
  _.sortBy(obj => comparator(items.length, _.get(key, obj)), tabs)
)
```

**Comment by daedalus28** [comment]
As far as I understand, we don't have this use case anymore and it's a bit complex - so without someone championing this, I'm going to close this to clean up the repo. We can revisit when and if there's popular support for it.
