### ISSUE TITLE
Add `recurry`

### ISSUE THREAD

**Issue by giulianok** [smartprocure/futil-js#179]
Add an uncurry fn

Example
`(n, f) => _.curry(R.uncurryN(n, f))`

**Comment by daedalus28** [comment]
Name should probably be `recurry`

**Comment by sharmaaditya570191** [comment]
Hi @daedalus28 . I have made a PR regarding this. Please have a look.

**Comment by daedalus28** [comment]
To further clarify, the use case is something like this:

If you define a method like this:

```js
let addToElements = (number, collection) = _.map(_.add(number), collection)
```
it could be reduced like this

```js
let addToElements = number = _.map(_.add(number))
// even simpler:
let addToElements = _.flow(_.add, _.map)
```

The challenge though is that all of those examples require being called with explicit curry only

```js
addToElements(5)([1, 2, 3]) // works
addToElements(5, [1, 2, 3]) //doesn't
```


So based on that a test case might look something like this so the method supports curried and uncurried invocation:

```js
let addToElements = F.recurry(2, _.flow(_.add, _.map))
expect(addToElements(5, [1, 2, 3])).to.deep.equal([6, 7, 8]])
expect(addToElements(5)([1, 2, 3])).to.deep.equal([6, 7, 8]])
```
