### ISSUE TITLE
F.postings hangs up if your regex doesn't have the g flag

### ISSUE THREAD

**Issue by doug-patterson** [smartprocure/futil-js#214]
`F.postings(/a/g, 'vuhfaof')` returns `[ [ 4, 5 ] ]`
`F.postings(/a/, 'vuhfaof')` never returns at all -- you're stuck in the while loop at https://github.com/smartprocure/futil-js/blob/master/src/regex.js#L42-L45 because without the `g` flag regex.exec() doesn't consume the initial match and so just finds it again forever.

Two possible fixes:
*  add the g flag before the while loop when needed with `regex = new RegExp(regex.source, regex.flags + 'g')`
   * downside: doesn't really give the behavior that would be expected by a person who on purpose didn't use the `g` flag. They're expecting the first match.
* check for the g flag. if it's not present, just return the rest of `.exec`-ing, else do the while loop
  * or equivalently have the while loop look at a boolean that you flip when you enter it.

Either fix is simple but I'll wait on feedback as to the preferred behavior.

**Comment by daedalus28** [comment]
If we check for the `g` flag and return the result of `exec`, we won't get the start and stop indexes as an array, but I do think that is right path (as long as the return type is the same). Having this method force `g` would probably be very unexpected
