### ISSUE TITLE
Misc improvements to documentation

### ISSUE THREAD

**Issue by stellarhoof** [smartprocure/futil-js#254]
It'd be useful for quickly browsing the documentation if:
1. Functions were sorted alphabetically
2. There was a search box to quickly zero-in on a given function.
3. Documentation could be exported to different formats for offline viewing (PDF, Markup, etc...)

**Comment by daedalus28** [comment]
Our plans for this are already outlined in #111

**Comment by daedalus28** [comment]
Feel feee to add additional notes there if we missed something
