### ISSUE TITLE
Add `compactMap`

### ISSUE THREAD

**Issue by michsa** [smartprocure/futil-js#266]
A function that maps over an array while [compacting](https://lodash.com/docs/#compact) it. Should avoid calling the iteratee on falsy values, and also omit them from the return array.

It would also make sense to add a generalized `mapSome` function (`mapWith`? `mapBy`?) that accepts a predicate for determining whether to include each element in the map, then just derive `compactMap` from it:

```
// mapSome :: predicate -> iteratee -> [a] -> [a]

compactMap = mapSome(_.identity)
```

**Comment by daedalus28** [comment]
“mapSome” would probably make sense to be called filteredMap, which would just be something like this:

```js
let filteredMap = _.curry(
  (predicate, transform, data) => _.flow(
    _.map(transform),
    _.filter(predicate)
  )(data)
)
```

**Comment by michsa** [comment]
I see two problems in that implementation: it maps over the dataset twice, and it calls the transform on elements that we're just going to filter out anyway.

One use case for this would be to map over mixed data where only some elements are compatible with the transform function (won't cause it to blow up or return unpredictable results). In the case of `compactMap`, that's non-nil values, though it could also be strings, non-empty arrays, objects with a certain key or property, etc...

To truly "map some", I believe we need a reduce. Here's what I've got, though (as usual) I think it can be cleaned up some (and it might be *less* efficient than mapping twice depending on how `_.concat` is implemented; I'll have to check):

```js
let mapSome = _.curry((predicate, transform, data) => _.reduce(
  (acc, x) => predicate(x) ? _.concat(acc, transform(x)) : acc, [], data
))
```

**Comment by michsa** [comment]
Actually, I suppose just swapping the order of `_.map` and `_.filter` in your flow would work too, as long as mapping twice is not an issue (and it probably isn't in the majority of cases, anyway)...

**Comment by daedalus28** [comment]
I'm not sure that makes sense because I would assume you'd want to filter based on the results of the transformation. For example, I would assume `compactMap('a', [{a:1}, {a:2}, {b:3}])` would return `[1, 2]`, not `[1, 2, undefined]`

**Comment by michsa** [comment]
Oh, good point on filtering results vs input. You're right, that's definitely what I'd expect from `compactMap` (I guess what I had in mind would be more like `mapTruthy`).

I still think a map that filters input could be useful, though. How about adding both?

**Comment by daedalus28** [comment]
I suppose the inverse you're suggestion might be called `mappedFilter` instead of `filteredMap`. `mapTruthy` is a bit ambiguous because it might imply that you're mapping _to_ truthy values 🤔, but that might just be nonsense. Least succinctly, it's `compactThenMap`. Maybe `mappedCompact` or even `mapCompact`?

**Comment by michsa** [comment]
With `mapOnly` instead of `mapSome`, you could go with a scheme like `mapOnlyTruthy`, `mapOnlyValidFilenames`, etc...

`compact` is kind of a bad example here, since it's just `filter(identity)`, which doesn't much benefit from the abstraction that `mapSome`/`mapOnly` is supposed to represent: "map this stuff, but only the parts that {predicate}".  Calling it `compactThenMap` (or its equivalent in any other case, `filterByXThenMap`), while technically accurate, breaks down that abstraction by describing the function imperatively, which is why it doesn't seem any more useful than an explicit flow.

On that note, I have no idea what kind of naming scheme we'd use for the rest of the functions returned by `filteredMap`. `validFilenameMap`? `validFilenameFilteredMap`?? 🤔
