### ISSUE TITLE
Let's pick a standardized JS style and stick with it

### ISSUE THREAD

**Issue by sadasant** [smartprocure/futil-js#35]
Since we're in favor of codeclimate, to see it's full potential and to increase sanity and simplicity for our current and future projects, we should pick a JavaScript style. [CodeClimate offers a list of eslint plugins that are supported](https://docs.codeclimate.com/docs/eslint#supported-plugins), and the ones that seem to be relevant for this purpose are:

- [airbnb](https://www.npmjs.com/package/eslint-config-airbnb).
- [google](https://www.npmjs.com/package/eslint-config-google).
- [standard](https://www.npmjs.com/package/eslint-config-standard).

There are also many other benefits of using standard stuff (pardon my laziness 🍭).

**Comment by sadasant** [comment]
Some pros & cons.

## [AirBnb](https://github.com/airbnb/javascript)

**pros**
- Fully strict ES6+.
**cons**
- Semicolons.
- Spaces before function parenthesis, unless arrow functions.
- 2 spaces.

# [Google](https://google.github.io/styleguide/jsguide.html)

**pros**
- Very specific but good uses of ES6+ tools, such as the spread operator.
- No spaces before function parenthesis.
**cons**
- Semicolons.
- Super extense 😱 
- 2 spaces.

# [Standard](http://standardjs.com/)

**pros**
- Has a npm module that could help us just ignore any eslint config.
- Outgrown AirBnb in popularity.
- Is the most forgiving with our existing code.
- No semicolons.
**cons**
- 2 spaces.
- Spaces before function parenthesis, unless arrow functions.

---

It's easy to ignore the 2spaces rule that all of them seem to use, but I would think a bout just using 2 spaces. The idea of using something standard is to think less on individual preferences around how things should look.

**Comment by daedalus28** [comment]
Vote here for AirBnb style

**Comment by daedalus28** [comment]
Vote here for Google style

**Comment by daedalus28** [comment]
Vote here for Standard style

**Comment by daedalus28** [comment]
Enough votes are in, JS standard style wins :)

**Comment by agamemnus** [comment]
!!!!! No semicolons??? :heart:

**Comment by sadasant** [comment]
yep!
