### ISSUE TITLE
Officially adopt standard js style

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/futil-js#40]
In #35 we picked standard js style. The the PR in #30 made us conform but we need to add our hard earned shiny readme badge 📛

**Comment by sadasant** [comment]
We have it here: https://github.com/smartprocure/futil-js/blame/master/README.md#L8

**Comment by sadasant** [comment]
Or do you prefer the other one?

**Comment by daedalus28** [comment]
You're right - good stuff 👍
