### ISSUE TITLE
Trampoline recursuve functions with trampoline

### ISSUE THREAD

**Issue by sadasant** [smartprocure/futil-js#55]
> A trampoline is a loop that iteratively invokes thunk-returning functions (continuation-passing style). A single trampoline is sufficient to express all control transfers of a program; a program so expressed is trampolined, or in trampolined style; converting a program to trampolined style is trampolining. Trampolined functions can be used to implement tail-recursive function calls in stack-oriented programming languages.–Wikipedia

See this post: http://raganwald.com/2013/03/28/trampolines-in-javascript.html

My dear friend @stefanmaric wrote a trampoline in this Gist:  https://gist.github.com/stefanmaric/1dfc01dd3985d5b423f22fcad7c58da2

```
const trampoline = (fn) => (...args) => {
  let result = fn(...args)
  while (result instanceof Function) result = result()
  return result
}
```

**Comment by daedalus28** [comment]
The goal of this library is to provide functions that aren't readily available in main-stream libraries, not to maintain our own versions of readily available utilities. Closing since trampolines are available in libraries lodash-contrib and underscore-contrib.
