### ISSUE TITLE
Housekeeping Issues

### ISSUE THREAD

**Issue by daedalus28** [smartprocure/futil-js#6]
- [x] Add a link to the changelog in the readme
- [x] Set up CI to auto publish to npm
- [x] Set up CI to auto run unit tests
- [x] Document all available methods

**Comment by daedalus28** [comment]
- [ ] CodeClimate
- [ ] Coveralls.io

**Comment by daedalus28** [comment]
Also greenkeeper doesn't seem to be actually working

**Comment by sadasant** [comment]
Do it for:
- [ ] https://github.com/smartprocure/eslint-config-smartprocure
- [ ] https://github.com/smartprocure/directory-metagen

**Comment by sadasant** [comment]
Codacy needs support for other eslint plugins, I submitted a PR: https://github.com/codacy/codacy-eslint/pull/39

**Comment by sadasant** [comment]
They merged my PR! 😄

**Comment by sadasant** [comment]
Some notes:
- Travis is awesome, we can make it do almost anything we need, the only caveat is that checking for build logs is obnoxious.
- Coveralls for code coverage is nice and pretty much automated, it might get spammy on most pull requests, but we can always remove extra comments.
- CodeClimate extension is super nice, but we haven't been able to set up code coverage with them, or eslint. Right now it's not even failing PRs. I will start contacting their support personal to see if we can get this to work.
- Codacy seems to work out of the box and do everything really nice as long as we use standard or commonly used eslint rules. It's a plus that we can propose changes to their public repos without hesitation; I proposed adding lodash and lodash-fp plugins yesterday and it got merged within the same day 👌 I think it's pretty cool that they did so, I can't overstate that enough 😂 but I might be biased at this point.

**Comment by sadasant** [comment]
CodeClimate answered my email, pushing up the bar! 😱😎

> I've cloned a copy of your repo and confirmed that the `Configuration for rule "mocha/no-exclusive-tests" is invalid:error` is happening because of a versioning issue with ESLint -- usually, you can specify the [eslint-2](https://docs.codeclimate.com/docs/eslint#section-eslint-versions) channel for the ESLint engine. 
>  
> After testing that change, however, I ran into this error:
`Error: Cannot find module 'eslint-config-smartprocure'`
In general, though, we don't currently support the eslint-config-smartprocure plugin in our ESLint 1, 2 or 3 channels. To get your ESLint config to work in Code Climate, you would either need to remove this plugin from your project, or disable ESLint. I'm sorry for this limitation in the meantime!
>  
> Right now, our ESLint engine supports a limited number of plugins. In case it's helpful, here's a full list of plugins we support via our ESLint engine: https://docs.codeclimate.com/docs/eslint#supported-plugins.
>  
> One thing I wanted to quick mention though was the goal when building our engines based analysis was to implement an open and extensible platform -- meaning that anyone could build support for a particular language or, in this case, a particular plugin into an existing engine. One thing you could potentially do would be to open a pull request against our ESLint engine's repo with support for that plugin you're using.
>  
> We don't currently have any step by step instructions on how to do this, but essentially you would add the packages to the package.json, regenerate the shrinkwrap file and open the pull request. Just so you can get an idea of what that would like, here's an example pull request where support for an ESLint plugin was added to our engine: https://github.com/codeclimate/codeclimate-eslint/pull/102/files. Depending on your familiarity with Node JS I suspect this would take less than an hour of engineering time to build. Once you open a pull request it's reviewed by our engineering team prior to being merged in.
>  
> Regarding test coverage, I recommend taking a look through this doc: https://docs.codeclimate.com/docs/travis-ci-javascript-test-coverage and making sure you're following the steps. I looked at your repo and it looks like you need to:
Add your repo token to your .travis.yml
Then add that after_success: node snipped mentioned in the doc to your .travis.yml

**Comment by daedalus28** [comment]
Looks like we've done all the things 👍
